name: CI

on:
  push:
    branches: [ "master" ]
    # Releases are tags named 'v<version>', and must have the "major.minor.micro", for example: "0.1.0".
    # Release candidates are tagged as `v<version>-rc<num>`, for example: "0.1.0-rc1".
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - --no-default-features
          - --features async
    steps:
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2023-10-21
        components: clippy
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build ${{ matrix.features }}
    - name: Clippy
      run: cargo clippy ${{ matrix.features }}
    - name: Run tests
      run: cargo test ${{ matrix.features }}
